# Generated by Django 3.1.6 on 2021-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=100)),
                ('phone', models.CharField(default='a', max_length=12)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='n/a', max_length=100)),
                ('team_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('teams', models.ManyToManyField(to='team.Person')),
            ],
        ),
    ]
