# Generated by Django 3.1.6 on 2021-02-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teams',
            new_name='persons',
        ),
    ]
